dist: trusty
language: node_js
node_js: '12.14.1'

cache:
  yarn: true
  directories:
    - node_modules

install:
  - npm install -g yarn
  - yarn install

script:
  - yarn run lint
  - yarn test
  - yarn run build
  - yarn run test-e2e

notifications:
  webhooks:
    urls:
      - https://open.feishu.cn/officialapp/notify/6fdda5e6dca387bd0b3937c8b2deb439327ae9ba27524f956a20127e24df68a5
    on_success: never # default: always
    on_failure: always # default: always
    on_start: never # default: never
    on_cancel: never # default: always
    on_error: always # default: always

